### ISSUE TITLE
Requires access administrator apparently doesn't have

### ISSUE THREAD

**Issue by Mooshimi** [RigglePrime/LogBuddy#4]
![image](https://user-images.githubusercontent.com/85910816/181414094-4ff0546d-d289-40d3-b79b-6c9a50278da8.png)
when running as admin straight from the folder and right clicking is gives this error
![image](https://user-images.githubusercontent.com/85910816/181414278-1e262535-53e9-47f3-a7e9-6ea7c5f14f24.png)
I feel stupid send help

**Comment by RigglePrime** [comment]
Wrong repo you dum. It's most likely an anti-virus issue. You can eithe try disabling it or running from source
